### ISSUE TITLE
github action 编译的二进制文件下载失效

### ISSUE THREAD

**Issue by iT-Boyer** [fastgitorg/fgit-rs#1]

**Comment by DuckSoft** [comment]
请提供具体的复现步骤。

**Comment by iT-Boyer** [comment]
gihub action显示下载过期了：
![截屏2020-11-24 上午10 17 43](https://user-images.githubusercontent.com/4022953/100038086-5abb3380-2e3e-11eb-8a71-672c5291b44b.png)
还有其他方式可以下载吗？

**Comment by DuckSoft** [comment]
看起来只能手动触发一次了。

**Comment by KevinZonda** [comment]
考虑到实现，目前依旧推荐尝试fgit-go -> https://github.com/FastGitORG/fgit-go
我现在去触发一次CI

**Comment by iT-Boyer** [comment]
嗯，看到二进制只有两个版本，linux 版本支持OS X运行吗？

**Comment by DuckSoft** [comment]
fgit-darwin-amd64

**Comment by iT-Boyer** [comment]
在哪能够下载 fgit-darwin-amd64

**Comment by KevinZonda** [comment]
> 在哪能够下载 fgit-darwin-amd64

额，rs版可能需要问一下维护者 @batkiz ，go版可以直接在release下，其他版本有类似自己的包管理？

**Comment by batkiz** [comment]
很抱歉，最近忙于学业，暂且没有精力进行维护。

新的可执行文件已由 @KevinZonda 触发 CI 生成，可以去 https://github.com/FastGitORG/fgit-rs/actions/runs/380202256 下载。

此外，由于维护者并没有 OS X 设备，无法进行测试，因此暂无直接提供 darwin 下可执行文件的计划。如有需要，可以考虑手动从源代码编译，这方面可以在网上找到很多文章（关键词： rust cargo build），我就不再赘述了。
